package enums;

public enum EAbility {

	PLUS_ONE_LIFE,
	PLUS_TWO_LIFE,
	PLUS_ONE_CARD,
	PLUS_TWO_CARDS,
	DESTROY_ONE,
	DOUBLE_ONE,
	COPY_ONE,
	PHASE_MINUS_ONE,
	SORT_THREE_CARDS,
	EXCHANGE_ONE,
	EXCHANGE_TWO,
	BELOW_THE_PILE_ONE,
	MINUS_ONE_LIFE,
	MINUS_TWO_LIFE,
	HIGHEST_CARD_EQUALS_ZERO,
	STOP,
	EACH_ADDITIONAL_FIGHTING_CARD_COSTS_TWO_LIFE_POINTS,
	PLUS_TWO_HAZARD_POINTS_FOR_EACH_AGING_CARD,
	EACH_FACE_UP_FIGHTING_CARD_COUNTS_PLUS_ONE_FIGHTING_POINT,
	ONLY_HALF_OF_THE_FACE_UP_FIGHTING_CARDS_COUNT,
	FIGHT_AGAINST_ALL_REMAINING_HAZARD_CARDS,

}
